import { createHash } from 'node:crypto';
import { escapeHTML as e, safeImageURL } from './lib.mjs';

const bookmark = '<svg viewBox="0 0 20 20" width="17" height="17" fill="none" stroke="currentColor" stroke-width="1.4" aria-hidden="true"><path d="M5 3.5h10v13l-5-3-5 3z"/></svg>';
const category = feed => feed.category ?? (feed.id === 'status' ? 'Status' : feed.type === 'Company' ? 'Official' : feed.topic === 'Safety & Society' ? 'Safety & Society' : 'Reporting');
export const renderNewsTabs = (newsUrl, socialUrl, active) => `<nav class="news-tabs" aria-label="News sections"><a href="${e(newsUrl)}" ${active === 'feeds' ? 'aria-current="page"' : ''}>Feeds</a><a href="${e(socialUrl)}" ${active === 'social' ? 'aria-current="page"' : ''}>Social</a></nav>`;
export function renderNewsPage({ news, feeds, timezone, sourceGuideUrl, newsUrl, socialUrl }) {
  const stamp = value => new Intl.DateTimeFormat('en-US', {timeZone:timezone,month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}).format(new Date(value));
  const updated = news.updatedAt ? stamp(news.updatedAt) : 'Not yet updated';
  const items = [...news.items].sort((a,b)=>b.publishedAt.localeCompare(a.publishedAt));
  const categories = [...new Set(feeds.map(category))];
  const story = item => `<article class="reader-story" data-story-id="${createHash('sha256').update(item.url).digest('hex').slice(0,16)}" data-source="${e(item.sourceId)}" data-published="${e(item.publishedAt)}" data-format="${item.format === 'video' ? 'video' : 'article'}"><button type="button" class="reader-read-dot" data-mark-read aria-label="Mark as read: ${e(item.title)}" data-reader-control hidden></button><div class="reader-story-content"><h4><a class="reader-story-link" href="${e(item.url)}" target="_blank" rel="noopener noreferrer">${safeImageURL(item.image) ? `<span class="reader-preview"><img src="${e(item.image)}" alt="" width="160" height="100" loading="lazy" decoding="async" referrerpolicy="no-referrer">${item.format === 'video' ? '<span class="reader-play" aria-hidden="true">▶</span>' : ''}</span>` : ''}<span class="reader-story-label"><span class="reader-story-title">${e(item.title)}</span><span class="story-external" aria-hidden="true">↗</span><span class="sr-only"> (opens in a new tab)</span></span></a></h4><div class="reader-story-meta"><span class="reader-story-source">${e(item.source)}</span><span class="reader-story-type">${e(item.type)}</span><time datetime="${e(item.publishedAt)}">${e(stamp(item.publishedAt))}</time></div></div><button class="reader-save" type="button" data-save-story aria-pressed="false" aria-label="Save: ${e(item.title)}" data-reader-control hidden>${bookmark}</button></article>`;
  return `<div class="reader" id="news-reader" data-timezone="${e(timezone)}">
    <header class="reader-heading"><div><div class="eyebrow">The feeds</div><h1>News</h1><p>Updated ${e(updated)} · <a class="reader-guide-link" href="${e(sourceGuideUrl)}">${feeds.length} sources ↗</a></p></div><label class="reader-search" data-reader-control hidden><svg viewBox="0 0 20 20" width="18" height="18" fill="none" stroke="currentColor" stroke-width="1.4" aria-hidden="true"><circle cx="8.5" cy="8.5" r="5.5"/><path d="m13 13 4 4"/></svg><span class="sr-only">Search headlines</span><input type="search" id="reader-search" placeholder="Search headlines" autocomplete="off"></label></header>${renderNewsTabs(newsUrl, socialUrl, 'feeds')}
    <div class="reader-layout"><aside class="reader-sidebar" aria-label="Feed navigation">
      <nav class="reader-views" aria-label="Your news" data-reader-control hidden><button type="button" data-reader-view="all" aria-pressed="true"><span class="nav-symbol" aria-hidden="true">▦</span>Overview<span class="reader-count">${items.length}</span></button><button type="button" data-reader-view="saved" aria-pressed="false">${bookmark}Saved<span class="reader-count" id="saved-count">0</span></button></nav>
      <div class="reader-nav-heading">Browse</div><nav class="reader-topics" aria-label="Feed categories" data-reader-control hidden>${categories.map(c=>`<button type="button" data-reader-category="${e(c)}" aria-pressed="false">${e(c)}</button>`).join('')}</nav>
      <div class="reader-nav-heading">Sources</div><nav class="reader-sources" aria-label="News sources" data-reader-control hidden>${feeds.map(f=>`<button type="button" data-reader-source="${e(f.id)}" aria-pressed="false"><span class="source-icon" data-source="${e(f.id)}" aria-hidden="true">${e(f.id==='google'?'↗':f.name.charAt(0))}</span><span class="source-name">${e(f.name)}</span></button>`).join('')}</nav>
      <label class="reader-mobile-source" data-reader-control hidden><span class="sr-only">Filter by source</span><select id="reader-source-select"><option value="">All sources</option>${feeds.map(f=>`<option value="${e(f.id)}">${e(f.name)}</option>`).join('')}</select></label>
      <details class="reader-feed-info"><summary>About the feeds</summary><p>Headlines open at their source. Google News links may redirect to the publisher. Saved stories and read status stay in this browser.</p>${feeds.map(f=>{const state=news.sources.find(s=>s.id===f.id);return `<p><a href="${e(f.site)}">${e(f.name)} ↗</a><small>${e(f.type)} · ${state?.status==='ok'?'Updated '+stamp(state.lastSuccessAt):'Unavailable; showing saved snapshot'}</small></p>`;}).join('')}</details>
    </aside><section class="reader-stream" aria-label="Headlines"><div class="reader-toolbar"><div><h2 id="reader-view-title">Overview</h2><span id="reader-result-count" role="status" aria-live="polite">${items.length} stories</span></div><div class="reader-toolbar-actions" data-reader-control hidden><button type="button" id="reader-unread" aria-pressed="false">Unread</button><div class="reader-layout-switch" aria-label="Headline layout"><button type="button" data-reader-layout="board" aria-pressed="true">By source</button><button type="button" data-reader-layout="latest" aria-pressed="false">Latest</button></div></div></div>
      <div id="reader-groups" class="reader-board">${feeds.map(f=>{const rows=items.filter(i=>i.sourceId===f.id);return `<section class="reader-panel" data-feed="${e(f.id)}" data-category="${e(category(f))}" data-name="${e(f.name)}"><header class="reader-panel-heading"><div><span class="source-icon" data-source="${e(f.id)}" aria-hidden="true">${e(f.id==='google'?'↗':f.name.charAt(0))}</span><div><h3>${e(f.name)}</h3><p>${e(f.type)}</p></div></div><a href="${e(f.site)}" target="_blank" rel="noopener noreferrer" aria-label="Visit ${e(f.name)} (opens in a new tab)">↗</a></header><div class="reader-panel-stories">${rows.map(story).join('')}</div><button type="button" class="reader-more" data-reader-more hidden>More from ${e(f.name)} <span aria-hidden="true">↓</span></button><p class="reader-panel-empty" ${rows.length?'hidden':''}>No headlines available.</p></section>`;}).join('')}</div>
      <div class="reader-empty" id="reader-empty" hidden><h3>No matching stories</h3><p>Try another source or a broader search.</p><button type="button" id="reader-clear">Clear filters</button></div><p class="reader-storage-note" id="reader-storage-note" role="status" hidden>Browser storage is unavailable. Saved and read stories will last for this visit only.</p>
    </section></div></div>`;
}

