import { escapeHTML as e, dateLabel } from './lib.mjs';

export function renderSourcesPage({ feeds, newsUrl, libraryUrls }) {
  const categories = [...new Set(feeds.map(feed => feed.category))];
  return `<div class="page-head"><h1>Sources</h1><p>Original reporting, useful experiments, and evidence worth reading.</p></div>
    <div class="position-note"><p>We select for original work, clear authorship, useful evidence, and relevance to people using AI. Company announcements, independent reporting, research, and advocacy serve different purposes; each is labeled. Inclusion does not mean agreement.</p></div>
    ${categories.map(category => `<section class="source-guide-group"><div class="section-head"><h2>${e(category)}</h2></div><div class="resource-list">${feeds.filter(feed => feed.category === category).map(feed => `<article class="resource" id="${e(feed.id)}"><div><div class="meta">${e(feed.type)}</div><h3><a href="${e(feed.site)}">${e(feed.name)} ↗</a></h3><p>${e(feed.description)}</p><p class="source-guide-context">${e(feed.notes)}</p><div class="meta">Reviewed ${dateLabel(feed.reviewedAt)} · <a href="${e(feed.url)}">RSS ↗</a></div></div></article>`).join('')}</div></section>`).join('')}
    <section class="source-guide-method prose"><h2>How we use them</h2><p>The reader links to recent headlines. It filters out items tagged as sponsored, removes duplicate stories, and gives each source its own space so frequent publishers do not crowd out slower research. Some linked articles require a subscription.</p><p>The Daily Brief has a separate editorial process: read original sources, search beyond the feeds, and choose the lead by public impact. A headline or a company's claim is a starting point for research.</p><p>Useful sources without a suitable feed belong in our libraries. Explore <a href="${e(libraryUrls.learn)}">courses and practical guides</a>, <a href="${e(libraryUrls.safety)}">safety research and policy</a>, <a href="${e(libraryUrls.projects)}">projects</a>, and <a href="${e(libraryUrls.money)}">business evidence</a>.</p><a class="text-link" href="${e(newsUrl)}">Back to the feeds →</a></section>`;
}
